### PR TITLE
Supresses a warning when running mix locally

### PR DESCRIPTION
**Pull request by floriank**
Small thing I saw when building it locally:

On `master`, you'll find this warning after running

```bash
$ mix deps.get && mix

# [...]
Warning: the `dialyxir` application's start function was called, which likely means you                
  did not add the dependency with the `runtime: false` flag. This is not recommended because                                                                                                                       
  it will mean that unnecessary applications are started, and unnecessary applications are most          
  likely being added to your PLT file, increasing build time.                                                                                                                                                      
  Please add `runtime: false` in your `mix.exs` dependency section e.g.:                                 
  {:dialyxir, "~> 0.5", only: [:dev], runtime: false}         
```

This adds the `runtime: false`, as recommended.

### CODE REVIEW

**Comment by asaaki** [comment]
Lemme merge #33 first, then you could rebase and update this PR?

**Comment by asaaki** [comment]
Ready for rebase. 🚀

**Comment by floriank** [comment]
rebased :rocket:

**Comment by asaaki** [comment]
Thank you for your contribution! 🙇

**Pull request merged**
